name: Deploy to Production

on:
    push:
        branches: [ master ]

env:
    NODE_VERSION: 24.x

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout Repository
                uses: actions/checkout@v3

            -   name: Setup Node.js Environment
                uses: actions/setup-node@v3
                with:
                    node-version: ${{ env.NODE_VERSION }}
                    cache: 'npm'

            -   name: Create .env.production file
                run: |
                    echo "VITE_APP_BASE_URL=${{ env.VITE_APP_BASE_URL }}" >> .env.production

            -   name: Install Dependencies
                run: npm ci

            -   name: Build for Production
                run: npm run build

            -   name: Deploy to Server
                uses: up9cloud/action-rsync@master
                env:
                    HOST: ${{ secrets.SSH_HOST }}
                    USER: ${{ secrets.SSH_USER }}
                    KEY: ${{secrets.SSH_PRIVATE_KEY}}
                    PORT: ${{ secrets.DEPLOY_PORT }}
                    SOURCE: ./dist/
                    TARGET: ${{ secrets.DEPLOY_PATH }}
